version: "3.7"
services:
  front-envoy:
    build: envoy
    volumes:
      - ./envoy/front-envoy.yml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  dogservice_envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./dogservice/envoy-config.yml:/etc/envoy-config.yaml
    expose:
      - "80"
      - "8002"
    ports:
      - "8002:8002"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info"
    networks:
      envoymesh:
        aliases:
          - dogservice_envoy

  catservice_envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./catservice/envoy-config.yml:/etc/envoy-config.yaml
    expose:
      - "80"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info"
    networks:
      envoymesh:
        aliases:
          - catservice_envoy

  dogservice:
    build: dogservice
    expose:
      - "8080"
    networks:
      envoymesh:
        aliases:
          - dogservice

  catservice:
    build: catservice
    expose:
      - "3000"
    networks:
      envoymesh:
        aliases:
          - catservice

networks:
  envoymesh: {}
